import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("http://192.168.10.230:30510/login")
    page.get_by_placeholder("请输入账号").click()
    page.get_by_placeholder("请输入账号").fill("13723945525")
    page.get_by_placeholder("请输入密码").click()
    page.get_by_placeholder("请输入密码").fill("Th#VHv1P6T3s53Ug")
    page.get_by_role("button", name="登录").click()
    page.get_by_text("新增项目").click()
    page.get_by_role("link", name="消防验收").click()
    page.get_by_role("textbox", name="请输入工程名称").click()
    page.get_by_role("textbox", name="请输入工程名称").fill("1010")
    page.locator("div").filter(has_text=re.compile(r"^类别：新建装修建筑保温用途变更扩建其他$")).get_by_placeholder("请选择").click()
    page.locator(".popper__arrow").click()
    page.locator("li").filter(has_text="新建").click()
    page.locator("li").filter(has_text="建筑保温").click()
    page.locator("div").filter(has_text="工程名称：工程地址：市辖区高新区芝罘区福山区牟平区莱山区蓬莱区经济技术开发区龙口市莱阳市莱州市招远市栖霞市海阳市类别：新建建筑保温建筑层数：建筑高度：建筑面积：").nth(3).click()
    page.get_by_role("textbox", name="请输入建筑层数").click()
    page.get_by_role("textbox", name="请输入建筑层数").fill("10")
    page.get_by_placeholder("请输入建筑高度").click()
    page.get_by_placeholder("请输入建筑高度").fill("10")
    page.get_by_text("工程名称：工程地址：市辖区高新区芝罘区福山区牟平区莱山区蓬莱区经济技术开发区龙口市莱阳市莱州市招远市栖霞市海阳市类别：新建建筑保温建筑层数：建筑高度：建筑面积：").click()
    page.get_by_placeholder("请输入建筑总面积").fill("10")
    page.get_by_placeholder("请输入建筑面积").click()
    page.get_by_placeholder("请输入建筑面积").fill("10")
    page.get_by_placeholder("请输入建筑体积").click()
    page.get_by_placeholder("请输入建筑体积").fill("10")
    page.get_by_text("暂 存提 交").click()
    page.get_by_placeholder("请选择").nth(1).click()
    page.locator("li").filter(has_text="工业").click()
    page.get_by_text("工程名称：工程地址：市辖区高新区芝罘区福山区牟平区莱山区蓬莱区经济技术开发区龙口市莱阳市莱州市招远市栖霞市海阳市类别：新建建筑保温建筑层数：建筑高度：建筑面积：").click()
    page.get_by_role("textbox", name="请输入，非必填").click()
    page.get_by_role("textbox", name="请输入，非必填").fill("10")
    page.get_by_placeholder("请输入建筑结构").click()
    page.get_by_placeholder("请输入建筑结构").fill("10")
    page.get_by_placeholder("请输入耐火等级").click()
    page.get_by_placeholder("请输入耐火等级").fill("10")
    page.get_by_role("textbox", name="请输入", exact=True).click()
    page.get_by_role("textbox", name="请输入", exact=True).fill("10")
    page.get_by_placeholder("选择日期").click()
    page.get_by_text("21", exact=True).click()
    page.get_by_placeholder("请输入，支持模糊查询").click()
    page.get_by_placeholder("请输入，支持模糊查询").fill("10")
    page.locator("div").filter(has_text=re.compile(r"^审查中心技术负责人：杨文明$")).get_by_placeholder("请选择").click()
    page.get_by_text("杨文明").click()
    page.get_by_role("button", name="提 交").click()
    page.get_by_role("button", name="确定").click()
    page.close()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
